### ISSUE TITLE
Publish Substrate Runtime Library Modules v1.0 to crates.io

### ISSUE THREAD

**Issue by gnunicorn** [substrate-developer-hub/hacktoberfest#1]
Required steps:

- Raise a PR against the substrate 1.0 branch that:
  - [ ] clean up dependency tree of sr- and srml-modules (see `cargo tree`)
  - [ ] Updates the license, description and other missing fields for each module (see `cargo package` warnings)
  - [ ] pins down versions of locally used dependencies
- Publish _(this can only be done by a Parity employee)_:
  - publish all srml-, sr- and dependent crates on crates.io (see `cargo publish`)
  - make sure [paritytech:core-devs](https://crates.io/teams/github:paritytech:core-devs) is one of the owners of the package on crates.io (see [`cargo owner`](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner))
 - Raise a PR against [the templates repository](https://github.com/shawntabrizi/substrate-package), replacing all published crates with version numbers

**Comment by bkchr** [comment]
Why do we want to encourage people to use packages that are outdated?

**Comment by gnunicorn** [comment]
The reasoning behind still publishing for now is in three parts:
1. people want to build on it, and for the templates and potential modules, they are pinning against a specific changeset anyways because staying up to date with master is just too much work. The feedback we've gotten is that they rather build something against a certain set now and then make a bigger update once a new release is there rather than attempting to stay up to date
2. the SR/SRML are overall rather stable (compared to core/node template) and an upgrade between 1.0 and 2.0 should not be too hard. 
3. it improves the experience for external development - if you build a runtime module right now, you _can't_ publish it on crates.io because it simply won't accept the git-based dependencies. Leaving the after taste of not really having completed the task.

Minor side arguments are, that we should have published before and that we _are_ for the sake of consistency and stability encouring building on non-master already. The counter questions would be: if we have  tagged and thus "released" a version 1.0 - and most of its dependency don't require github links: _Why isn't it published already?_

**Comment by gnunicorn** [comment]
Turns out this can't be done for version 1.0 unless we also resolve the kvdb-memorydb github-reference. One wouldn't expect that but because the srml depending on core/primitives -> core/trie -> core/cli -> core/client we end up with kvdb-memorydb as a dev-dependency and that ... links to a github ref. so we can't publish the srml on crates.io at the moment :( .
