### ISSUE TITLE
[Runtime Module] Name Registry

### ISSUE THREAD

**Issue by gnunicorn** [substrate-developer-hub/hacktoberfest#20]
Often one needs a globally unique registry to map names to values - for example for DNS. Implementing that as a generic runtime module with different access control flows would be great.

This module should be generic over the value each entry stores and it would be great if it would come with facilities to allow for different claim and update mechanism. For example a domain might be auctioned off at the beginning and only the winner can write and update that entry. Aside from a few common installments the repo should only show them and allow for other strategies to be implemented.

For mentoring this issue please contact: [me, @gnunicorn ](https://substrate.dev/hacktoberfest/hackers/gnunicorn.html)

## Proof of done

 - [ ] Create a new project by copying the [contents from our runtime module template](https://github.com/substrate-developer-hub/substrate-module-template)
 - [ ] Don't forget to add an OpenSource License !
 - [ ] Implement the specific module
 - [ ] Once done, submit a PR with your module published on openly on github as a git submodule under `submissions`

**Comment by hskang9** [comment]
I started working on this with https://github.com/hskang9/naming-service-module. When I was trying to use other traits, after importing packages(balances, timestamp) from SRML, the current repo supports system::Trait and creates error. Is there any way to support other SRMLs?

**Comment by hskang9** [comment]
Current work is with node template and working well!

[link](https://github.com/hskang9/naming-service-node-template)
![](https://i.imgur.com/9lycNid.png)
