### ISSUE TITLE
Detection of cargo-web during compilation.

### ISSUE THREAD

**Issue by himanshu1root** [substrate-developer-hub/hacktoberfest#35]
The most important problem or a part we can say it to detect cargo-web during the compilation so this is the way we can detect cargo-web during compilation:
If during compilation you'd like to detect that your project is being built with cargo-web you can check the COMPILING_UNDER_CARGO_WEB environment variable, which will be set to 1.

##Label_hacktoberfest

**Comment by riusricardo** [comment]
Can you elaborate? I'm trying to understand where does this issue stands on our repos/docs/etc...
